// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// em_pava
SEXP em_pava(SEXP pa_in, SEXP pb_in, SEXP x_in, SEXP pi0a_in, SEXP pi0b_in, SEXP pi0x_in);
RcppExport SEXP _coconut_em_pava(SEXP pa_inSEXP, SEXP pb_inSEXP, SEXP x_inSEXP, SEXP pi0a_inSEXP, SEXP pi0b_inSEXP, SEXP pi0x_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pa_in(pa_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pb_in(pb_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi0a_in(pi0a_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi0b_in(pi0b_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi0x_in(pi0x_inSEXP);
    rcpp_result_gen = Rcpp::wrap(em_pava(pa_in, pb_in, x_in, pi0a_in, pi0b_in, pi0x_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coconut_em_pava", (DL_FUNC) &_coconut_em_pava, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_coconut(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
