# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_pava <- function(pa_in, pb_in, x_in, pi0a_in, pi0b_in, pi0x_in) {
    .Call(`_coconut_em_pava`, pa_in, pb_in, x_in, pi0a_in, pi0b_in, pi0x_in)
}

